//
// Generated by JTB 1.3.2
//

import syntaxtree.*;
import visitor.GJVisitor;

import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class OutputGenerator<R,A> implements GJVisitor<R,A> {
    //
    // Auto class visitors--probably don't need to be overridden.
    //
    private String currentClassName;
    private String currentMethodName;
    private Boolean inFieldLookup = false;
    private HashMap<String, ArrayList<String>> outputDS = new HashMap<String, ArrayList<String>>(); // map of method name to List of references in the method

    public R visit(NodeList n, A argu) {
        R _ret=null;
        int _count=0;
        for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
        }
        return _ret;
    }

    public R visit(NodeListOptional n, A argu) {
        if ( n.present() ) {
            R _ret=null;
            int _count=0;
            for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
                e.nextElement().accept(this,argu);
                _count++;
            }
            return _ret;
        }
        else
            return null;
    }

    public R visit(NodeOptional n, A argu) {
        if ( n.present() )
            return n.node.accept(this,argu);
        else
            return null;
    }

    public R visit(NodeSequence n, A argu) {
        R _ret=null;
        int _count=0;
        for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
        }
        return _ret;
    }

    public R visit(NodeToken n, A argu) { return null; }

    //
    // User-generated visitor methods below
    //

    /**
     * f0 -> MainClass()
     * f1 -> ( TypeDeclaration() )*
     * f2 -> <EOF>
     */
    public R visit(Goal n, A argu) {
        Bindings bindings = (Bindings) argu;
        HashMap<String, ClassResource> binds = bindings.getBindings();


        for (Map.Entry<String,ClassResource> entry : binds.entrySet()){
            String className = entry.getKey();
            ClassResource classResource = entry.getValue();
            Map<String, MethodMetadata> methodMetadataMap = classResource.getMethodMetadata();
            for (Map.Entry<String, MethodMetadata> methodEntry : methodMetadataMap.entrySet()) {
                String methodName = methodEntry.getKey();
                MethodMetadata methodMetadata = methodEntry.getValue();
                if (methodName == "main" || methodMetadata.getOriginClass() != className) continue;
                String key = className + "." + methodName;
                outputDS.put(key, new ArrayList<>()); // Initialize an empty list for each method
            }
        }
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);

        // Sort outputDS by keys (method names) lexicographically
        TreeMap<String, ArrayList<String>> sortedOutputDS = new TreeMap<>(outputDS);

// Write the logic to print the sortedOutputDS
        for (Map.Entry<String, ArrayList<String>> entry : sortedOutputDS.entrySet()) {
            String methodKey = entry.getKey();
            ArrayList<String> references = entry.getValue();

            // Skip printing if the references list is empty
            if (references.isEmpty()) {
                continue;
            }

            System.out.println(methodKey + ":");
            for (String reference : references) {
                System.out.println(reference);
            }
        }

        return _ret;
    }

    /**
     * f0 -> "public"
     * f1 -> "class"
     * f2 -> Identifier()
     * f3 -> "{"
     * f4 -> "public"
     * f5 -> "static"
     * f6 -> "void"
     * f7 -> "main"
     * f8 -> "("
     * f9 -> "String"
     * f10 -> "["
     * f11 -> "]"
     * f12 -> Identifier()
     * f13 -> ")"
     * f14 -> "{"
     * f15 -> ( VarDeclaration() )*
     * f16 -> ( Statement() )*
     * f17 -> "}"
     * f18 -> "}"
     */
    public R visit(MainClass n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        n.f6.accept(this, argu);
        n.f7.accept(this, argu);
        n.f8.accept(this, argu);
        n.f9.accept(this, argu);
        n.f10.accept(this, argu);
        n.f11.accept(this, argu);
        n.f12.accept(this, argu);
        n.f13.accept(this, argu);
        n.f14.accept(this, argu);
        n.f15.accept(this, argu);
        n.f16.accept(this, argu);
        n.f17.accept(this, argu);
        n.f18.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> ClassDeclaration()
     *       | ClassExtendsDeclaration()
     */
    public R visit(TypeDeclaration n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "class"
     * f1 -> Identifier()
     * f2 -> "{"
     * f3 -> ( VarDeclaration() )*
     * f4 -> ( MethodDeclaration() )*
     * f5 -> "}"
     */
    public R visit(ClassDeclaration n, A argu) {
        currentClassName = n.f1.f0.tokenImage;
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        currentClassName = null;
        return _ret;
    }

    /**
     * f0 -> "class"
     * f1 -> Identifier()
     * f2 -> "extends"
     * f3 -> Identifier()
     * f4 -> "{"
     * f5 -> ( VarDeclaration() )*
     * f6 -> ( MethodDeclaration() )*
     * f7 -> "}"
     */
    public R visit(ClassExtendsDeclaration n, A argu) {
        currentClassName = n.f1.f0.tokenImage;
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        n.f6.accept(this, argu);
        n.f7.accept(this, argu);
        currentClassName = null;
        return _ret;
    }

    /**
     * f0 -> Type()
     * f1 -> Identifier()
     * f2 -> ";"
     */
    public R visit(VarDeclaration n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "public"
     * f1 -> Type()
     * f2 -> Identifier()
     * f3 -> "("
     * f4 -> ( FormalParameterList() )?
     * f5 -> ")"
     * f6 -> "{"
     * f7 -> ( VarDeclaration() )*
     * f8 -> ( Statement() )*
     * f9 -> "}"
     */
    public R visit(MethodDeclaration n, A argu) {
        inFieldLookup = true;
        currentMethodName = n.f2.f0.tokenImage;

        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        n.f6.accept(this, argu);

        n.f7.accept(this, argu);
        inFieldLookup = false;

        n.f8.accept(this, argu);
        n.f9.accept(this, argu);

        currentMethodName = null;
        return _ret;
    }

    /**
     * f0 -> FormalParameter()
     * f1 -> ( FormalParameterRest() )*
     */
    public R visit(FormalParameterList n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Type()
     * f1 -> Identifier()
     */
    public R visit(FormalParameter n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> ","
     * f1 -> FormalParameter()
     */
    public R visit(FormalParameterRest n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> BooleanType()
     *       | IntegerType()
     *       | VoidType()
     *       | Identifier()
     */
    public R visit(Type n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "boolean"
     */
    public R visit(BooleanType n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "int"
     */
    public R visit(IntegerType n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "void"
     */
    public R visit(VoidType n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Block()
     *       | ReturnStatement()
     *       | AssignmentStatement()
     *       | MessageSendStatement()
     *       | FieldStoreStatement()
     *       | IfStatement()
     *       | WhileStatement()
     *       | PrintStatement()
     */
    public R visit(Statement n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "{"
     * f1 -> ( Statement() )*
     * f2 -> "}"
     */
    public R visit(Block n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "return"
     * f1 -> Expression()
     * f2 -> ";"
     */
    public R visit(ReturnStatement n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "="
     * f2 -> Expression()
     * f3 -> ";"
     */
    public R visit(AssignmentStatement n, A argu) {

        // Continue processing other parts of the statement (if needed)
        R _ret = null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        return _ret;
    }



    /**
     * f0 -> BaseExpression()
     * f1 -> "."
     * f2 -> Identifier()
     * f3 -> "="
     * f4 -> Expression()
     * f5 -> ";"
     */
    public R visit(FieldStoreStatement n, A argu) {
        inFieldLookup = true;
        Bindings bindings = (Bindings) argu;
        String declaredType = "";
        String varname = "";
        if(n.f0.f0.choice instanceof Identifier){
            Identifier identifier = (Identifier) n.f0.f0.choice;
            varname = identifier.f0.tokenImage;
            declaredType = bindings.lookupVariable(currentClassName, currentMethodName, varname);
        } else if (n.f0.f0.choice instanceof ThisExpression) {
            declaredType = currentClassName;
            varname = "this";
        }

        String fieldName = n.f2.f0.tokenImage;
        declaredType = bindings.lookupFieldOnly(declaredType,currentMethodName,fieldName);
        String op = varname + "." + fieldName + " = " + declaredType + "." + fieldName;
        String key = currentClassName + "." + currentMethodName;

        outputDS.get(key).add(op);
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        inFieldLookup = false;
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> BaseExpression()
     * f1 -> "."
     * f2 -> Identifier()
     * f3 -> "("
     * f4 -> ( ExpressionList() )?
     * f5 -> ")"
     * f6 -> ";"
     */

    public R visit(MessageSendStatement n, A argu) {
        Bindings bindings = (Bindings) argu;
        String declaredType = "";
        String varname = "";

        // Resolve variable or `this` for the method call
        if (n.f0.f0.choice instanceof Identifier) {
            Identifier identifier = (Identifier) n.f0.f0.choice;
            varname = identifier.f0.tokenImage;
            declaredType = bindings.lookupVariable(currentClassName, currentMethodName, varname);
        } else if (n.f0.f0.choice instanceof ThisExpression) {
            declaredType = currentClassName;
            varname = "this";
        }

        // Resolve method origin
        String calledMethodName = n.f2.f0.tokenImage;

        // Collect possible types (e.g., considering overridden methods)
        List<String> possibleTypes = bindings.lookupPossibleTypes(declaredType, calledMethodName);
        Collections.sort(possibleTypes);  // This sorts the list of possible types

        // Build the operation string
        StringBuilder whtgoeesinBuilder = new StringBuilder();
        for (int i = 0; i < possibleTypes.size(); i++) {
            whtgoeesinBuilder.append(possibleTypes.get(i)).append(".").append(calledMethodName);
            if (i < possibleTypes.size() - 1) {
                whtgoeesinBuilder.append(", ");
            }
        }
        if (currentClassName != null && currentMethodName != null) {
            String key = currentClassName + "." + currentMethodName;
            outputDS.computeIfAbsent(key, k -> new ArrayList<>()).add(varname + "." + calledMethodName + " = [" + whtgoeesinBuilder + "]");
        }
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        n.f6.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> IfthenElseStatement()
     *       | IfthenStatement()
     */
    public R visit(IfStatement n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "if"
     * f1 -> "("
     * f2 -> Identifier()
     * f3 -> ")"
     * f4 -> Statement()
     */
    public R visit(IfthenStatement n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "if"
     * f1 -> "("
     * f2 -> Identifier()
     * f3 -> ")"
     * f4 -> Statement()
     * f5 -> "else"
     * f6 -> Statement()
     */
    public R visit(IfthenElseStatement n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        n.f6.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "while"
     * f1 -> "("
     * f2 -> Identifier()
     * f3 -> ")"
     * f4 -> Statement()
     */
    public R visit(WhileStatement n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "System.out.println"
     * f1 -> "("
     * f2 -> Expression()
     * f3 -> ")"
     * f4 -> ";"
     */
    public R visit(PrintStatement n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> OrExpression()
     *       | AndExpression()
     *       | CompareExpression()
     *       | NeqExpression()
     *       | PlusExpression()
     *       | MinusExpression()
     *       | TimesExpression()
     *       | DivExpression()
     *       | MessageSend()
     *       | FieldLookup()
     *       | PrimaryExpression()
     */
    public R visit(Expression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "&&"
     * f2 -> PrimaryExpression()
     */
    public R visit(AndExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "||"
     * f2 -> PrimaryExpression()
     */
    public R visit(OrExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "<="
     * f2 -> PrimaryExpression()
     */
    public R visit(CompareExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "!="
     * f2 -> PrimaryExpression()
     */
    public R visit(NeqExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "+"
     * f2 -> PrimaryExpression()
     */
    public R visit(PlusExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "-"
     * f2 -> PrimaryExpression()
     */
    public R visit(MinusExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "*"
     * f2 -> PrimaryExpression()
     */
    public R visit(TimesExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> PrimaryExpression()
     * f1 -> "/"
     * f2 -> PrimaryExpression()
     */
    public R visit(DivExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "."
     * f2 -> Identifier()
     */
    public R visit(FieldLookup n, A argu) {
        inFieldLookup = true;
        Bindings bindings = (Bindings) argu;

        String varName = n.f0.f0.tokenImage; // Variable being dereferenced
        String declaredType = bindings.lookupVariable(currentClassName, currentMethodName, varName);


        // Get the field name being accessed (e.g., `f2` in `a1.f2`)
        String fieldName = n.f2.f0.tokenImage;
        declaredType = bindings.lookupFieldOnly(declaredType,currentMethodName,fieldName);
        // Generate the dereference operation
        String operation = varName + "." + fieldName + " = " + declaredType + "." + fieldName;

        // Store the operation in the outputDS under the current method
        String key = currentClassName + "." + currentMethodName;
        outputDS.computeIfAbsent(key, k -> new ArrayList<>()).add(operation);

        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        inFieldLookup = false;
        return _ret;
    }

    /**
     * f0 -> BaseExpression()
     * f1 -> "."
     * f2 -> Identifier()
     * f3 -> "("
     * f4 -> ( ExpressionList() )?
     * f5 -> ")"
     */
    public R visit(MessageSend n, A argu) {
        Bindings bindings = (Bindings) argu;
        String declaredType = "";
        String varname = "";

        // Resolve variable or `this` for the method call
        if (n.f0.f0.choice instanceof Identifier) {
            Identifier identifier = (Identifier) n.f0.f0.choice;
            varname = identifier.f0.tokenImage;
            declaredType = bindings.lookupVariable(currentClassName, currentMethodName, varname);
        } else if (n.f0.f0.choice instanceof ThisExpression) {
            declaredType = currentClassName;
            varname = "this";
        }

        // Resolve method origin
        String calledMethodName = n.f2.f0.tokenImage;

        // Collect possible types (e.g., considering overridden methods)
        List<String> possibleTypes = bindings.lookupPossibleTypes(declaredType, calledMethodName);

        // Build the operation string
        StringBuilder whtgoeesinBuilder = new StringBuilder();
        for (int i = 0; i < possibleTypes.size(); i++) {
            whtgoeesinBuilder.append(possibleTypes.get(i)).append(".").append(calledMethodName);
            if (i < possibleTypes.size() - 1) {
                whtgoeesinBuilder.append(", ");
            }
        }
// Store the operation, ensuring we skip `null.null`
        if (currentClassName != null && currentMethodName != null) {
            String key = currentClassName + "." + currentMethodName;
            outputDS.computeIfAbsent(key, k -> new ArrayList<>()).add(varname + "." + calledMethodName + " = [" + whtgoeesinBuilder + "]");
        }


        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Expression()
     * f1 -> ( ExpressionRest() )*
     */
    public R visit(ExpressionList n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> ","
     * f1 -> Expression()
     */
    public R visit(ExpressionRest n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> TrueLiteral()
     *       | FalseLiteral()
     *       | IntegerLiteral()
     *       | Identifier()
     *       | ThisExpression()
     *       | AllocationExpression()
     *       | NotExpression()
     *       | BracketExpression()
     */
    public R visit(PrimaryExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     *       | ThisExpression()
     */
    public R visit(BaseExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> <INTEGER_LITERAL>
     */
    public R visit(IntegerLiteral n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "true"
     */
    public R visit(TrueLiteral n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "false"
     */
    public R visit(FalseLiteral n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> <IDENTIFIER>
     */
    public R visit(Identifier n, A argu) {
        if (!inFieldLookup) {
            Bindings bindings = (Bindings) argu;

            if (currentClassName != null && currentMethodName != null && currentMethodName != "main"){
                String varname = n.f0.tokenImage;
                String fieldClass = bindings.lookupFieldOnly(currentClassName,currentMethodName,varname);
                if (fieldClass != null){
                    String operation = varname + " = " + fieldClass + "." + varname;
                    String key = currentClassName + "." + currentMethodName;
                    outputDS.computeIfAbsent(key, k -> new ArrayList<>()).add(operation);
                }

            }
        }

        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "this"
     */
    public R visit(ThisExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "new"
     * f1 -> Identifier()
     * f2 -> "("
     * f3 -> ")"
     */
    public R visit(AllocationExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "!"
     * f1 -> Expression()
     */
    public R visit(NotExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "("
     * f1 -> Expression()
     * f2 -> ")"
     */
    public R visit(BracketExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

}
