//
// Generated by JTB 1.3.2
//

import syntaxtree.*;
import visitor.Visitor;

import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class OutputGenerator implements Visitor {
    Map<String, String> registerAllocation;
    Map<String,String> typeMap;
    String currentClass = null;
    String currentMethod = null;
    int numRegisters;
    public OutputGenerator(Map<String, String> registerAllocation) {
        this.registerAllocation = registerAllocation;
        typeMap = new HashMap<>();
    }

    //
    // Auto class visitors--probably don't need to be overridden.
    //
    public void visit(NodeList n) {
        for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
    }

    public void visit(NodeListOptional n) {
        if ( n.present() )
            for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
                e.nextElement().accept(this);
    }

    public void visit(NodeOptional n) {
        if ( n.present() )
            n.node.accept(this);
    }

    public void visit(NodeSequence n) {
        for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
    }

    public void visit(NodeToken n) { }

    //
    // User-generated visitor methods below
    //

    /**
     * f0 -> <REGLIMIT>
     * f1 -> MainClass()
     * f2 -> ( TypeDeclaration() )*
     * f3 -> <EOF>
     */
    public void visit(Goal n) {
        String firstLine = n.f0.tokenImage;
        String numString = firstLine.substring(firstLine.indexOf("/*") + 2, firstLine.indexOf("*/"));
        numRegisters = Integer.parseInt(numString);
        System.out.println(firstLine);
        System.out.println("import static a3.Memory.*;");
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
    }

    /**
     * f0 -> "class"
     * f1 -> Identifier()
     * f2 -> "{"
     * f3 -> "public"
     * f4 -> "static"
     * f5 -> "void"
     * f6 -> "main"
     * f7 -> "("
     * f8 -> "String"
     * f9 -> "["
     * f10 -> "]"
     * f11 -> Identifier()
     * f12 -> ")"
     * f13 -> "{"
     * f14 -> ( VarDeclaration() )*
     * f15 -> ( Statement() )*
     * f16 -> "}"
     * f17 -> "}"
     */
    public void visit(MainClass n) {
        currentClass = n.f1.f0.tokenImage;
        currentMethod = "main";
        System.out.println("class " + n.f1.f0.tokenImage + " {");
        System.out.println("\t public static void main(String[] " + n.f11.f0.tokenImage + ") {");
        addRegDeclAndAlloc();

        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        n.f6.accept(this);
        n.f7.accept(this);
        n.f8.accept(this);
        n.f9.accept(this);
        n.f10.accept(this);
        n.f11.accept(this);
        n.f12.accept(this);
        n.f13.accept(this);
        n.f14.accept(this);
        n.f15.accept(this);
        n.f16.accept(this);
        n.f17.accept(this);
        System.out.println("\t }");
        System.out.println("}");
        currentMethod = null;
        currentClass = null;
    }


    /**
     * f0 -> ClassDeclaration()
     *       | ClassExtendsDeclaration()
     */
    public void visit(TypeDeclaration n) {
        n.f0.accept(this);
    }

    /**
     * f0 -> "class"
     * f1 -> Identifier()
     * f2 -> "{"
     * f3 -> ( VarDeclaration() )*
     * f4 -> ( MethodDeclaration() )*
     * f5 -> "}"
     */
    public void visit(ClassDeclaration n) {
        System.out.println("class " + n.f1.f0.tokenImage + "{");
        currentClass = n.f1.f0.tokenImage;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        System.out.println("}");
        currentClass = null;
    }

    /**
     * f0 -> "class"
     * f1 -> Identifier()
     * f2 -> "extends"
     * f3 -> Identifier()
     * f4 -> "{"
     * f5 -> ( VarDeclaration() )*
     * f6 -> ( MethodDeclaration() )*
     * f7 -> "}"
     */
    public void visit(ClassExtendsDeclaration n) {
        System.out.println("class " + n.f1.f0.tokenImage + " extends" + n.f3.f0.tokenImage + "{");

        currentClass = n.f1.f0.tokenImage;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        n.f6.accept(this);
        n.f7.accept(this);
        System.out.println("}");
        currentClass = null;
    }

    /**
     * f0 -> Type()
     * f1 -> Identifier()
     * f2 -> ";"
     */
    public void visit(VarDeclaration n) {
        String unambiguousVariableName = currentClass + "." + currentMethod +"." + n.f1.f0.tokenImage;
        typeMap.put(unambiguousVariableName,resolveType(n.f0));
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
    }

    /**
     * f0 -> "public"
     * f1 -> Type()
     * f2 -> Identifier()
     * f3 -> "("
     * f4 -> ( FormalParameterList() )?
     * f5 -> ")"
     * f6 -> "{"
     * f7 -> ( VarDeclaration() )*
     * f8 -> ( Statement() )*
     * f9 -> "return"
     * f10 -> Identifier()
     * f11 -> ";"
     * f12 -> "}"
     */
    public void visit(MethodDeclaration n) {
        System.out.print("public " + resolveType(n.f1) + " " + n.f2.f0.tokenImage + "(");
        currentMethod = n.f2.f0.tokenImage;
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        n.f6.accept(this);
        System.out.println("){");
        addRegDeclAndAlloc();
        n.f7.accept(this);
        n.f8.accept(this);
        n.f9.accept(this);
        n.f10.accept(this);
        n.f11.accept(this);
        n.f12.accept(this);
        System.out.println("return " + replaceIdentifier(n.f10.f0.tokenImage) + ";");
        System.out.println("}");
        currentMethod = null;
    }



    /**
     * f0 -> FormalParameter()
     * f1 -> ( FormalParameterRest() )*
     */
    public void visit(FormalParameterList n) {
        n.f0.accept(this);
        n.f1.accept(this);
    }

    /**
     * f0 -> Type()
     * f1 -> Identifier()
     */
    public void visit(FormalParameter n) {
        System.out.print(resolveType(n.f0) + " " + n.f1.f0.tokenImage);
        n.f0.accept(this);
        n.f1.accept(this);
    }

    /**
     * f0 -> ","
     * f1 -> FormalParameter()
     */
    public void visit(FormalParameterRest n) {
        System.out.print(",");
        n.f0.accept(this);
        n.f1.accept(this);
    }

    /**
     * f0 -> ArrayType()
     *       | BooleanType()
     *       | IntegerType()
     *       | FloatType()
     *       | Identifier()
     */
    public void visit(Type n) {
        n.f0.accept(this);
    }

    /**
     * f0 -> "int"
     * f1 -> "["
     * f2 -> "]"
     */
    public void visit(ArrayType n) {
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
    }

    /**
     * f0 -> "float"
     */
    public void visit(FloatType n) {
        n.f0.accept(this);
    }

    /**
     * f0 -> "boolean"
     */
    public void visit(BooleanType n) {
        n.f0.accept(this);
    }

    /**
     * f0 -> "int"
     */
    public void visit(IntegerType n) {
        n.f0.accept(this);
    }

    /**
     * f0 -> Block()
     *       | AssignmentStatement()
     *       | ArrayAssignmentStatement()
     *       | FieldAssignmentStatement()
     *       | IfStatement()
     *       | WhileStatement()
     *       | PrintStatement()
     *       | LivenessQueryStatement()
     */
    public void visit(Statement n) {
        n.f0.accept(this);
    }

    /**
     * f0 -> "{"
     * f1 -> ( Statement() )*
     * f2 -> "}"
     */
    public void visit(Block n) {
        System.out.println("{");
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        System.out.println("}");
    }

    /**
     * f0 -> Identifier()
     * f1 -> "="
     * f2 -> Expression()
     * f3 -> ";"
     */
    public void visit(AssignmentStatement n) {
        String unambiguousVariableName = currentClass + "." + currentMethod + "." + n.f0.f0.tokenImage;
        String ra = registerAllocation.get(unambiguousVariableName);
        Boolean isSpilled = true;
        Boolean nonLiveVar = false;
        if (ra == null){
            nonLiveVar = true;
        } else{
            if (ra.contains("R")){
                isSpilled = false;
                System.out.print(ra + " = ");
            } else{
                int spillIndex = Integer.parseInt(ra);
                System.out.print("store(" + spillIndex + ",");
            }
            if (n.f2.f0.choice instanceof PrimaryExpression){
                PrimaryExpression primaryExpression = (PrimaryExpression) n.f2.f0.choice;
                if (primaryExpression.f0.choice instanceof Identifier){
                    Identifier identifier = (Identifier) primaryExpression.f0.choice;
                    System.out.print(replaceIdentifier(identifier.f0.tokenImage));
                }
            }
        }

        n.f0.accept(this);
        n.f1.accept(this);
        if (!nonLiveVar){
            n.f2.accept(this);
            if (isSpilled){
                System.out.print(")");
            }
            System.out.println(";");
        }
        n.f3.accept(this);

    }

    /**
     * f0 -> Identifier()
     * f1 -> "["
     * f2 -> Identifier()
     * f3 -> "]"
     * f4 -> "="
     * f5 -> Identifier()
     * f6 -> ";"
     */
    public void visit(ArrayAssignmentStatement n) {
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
        n.f6.accept(this);
    }

    /**
     * f0 -> Identifier()
     * f1 -> "."
     * f2 -> Identifier()
     * f3 -> "="
     * f4 -> Identifier()
     * f5 -> ";"
     */
    public void visit(FieldAssignmentStatement n) {
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        n.f5.accept(this);
    }

    /**
     * f0 -> IfthenElseStatement()
     *       | IfthenStatement()
     */
    public void visit(IfStatement n) {
        n.f0.accept(this);
    }

    /**
     * f0 -> "if"
     * f1 -> "("
     * f2 -> Identifier()
     * f3 -> ")"
     * f4 -> Statement()
     */
    public void visit(IfthenStatement n) {
        System.out.print("if(");
        System.out.println(replaceIdentifier(n.f2.f0.tokenImage) + "){");
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        System.out.println("}");
    }

    /**
     * f0 -> "if"
     * f1 -> "("
     * f2 -> Identifier()
     * f3 -> ")"
     * f4 -> Statement()
     * f5 -> "else"
     * f6 -> Statement()
     */
    public void visit(IfthenElseStatement n) {
        System.out.print("if(");
        System.out.println(replaceIdentifier(n.f2.f0.tokenImage) + "){");
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        System.out.println("} else {");
        n.f5.accept(this);
        n.f6.accept(this);
        System.out.println("}");
    }

    /**
     * f0 -> "while"
     * f1 -> "("
     * f2 -> Identifier()
     * f3 -> ")"
     * f4 -> Statement()
     */
    public void visit(WhileStatement n) {
        System.out.print("while(");
//        System.out.print("------");
//        if (n.f4.f0.choice instanceof Block){
//            System.out.println("HEHEHEHE --------");
//        }
        System.out.println(replaceIdentifier(n.f2.f0.tokenImage) + "){");
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        System.out.println("}");
    }

    /**
     * f0 -> "System.out.println"
     * f1 -> "("
     * f2 -> Identifier()
     * f3 -> ")"
     * f4 -> ";"
     */
    public void visit(PrintStatement n) {
        System.out.println("System.out.println(" + replaceIdentifier(n.f2.f0.tokenImage) + ");");
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
    }



    /**
     * f0 -> <SCOMMENT1>
     * f1 -> <LIVENESSQUERY>
     * f2 -> <SCOMMENT2>
     */
    public void visit(LivenessQueryStatement n) {
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
    }

    /**
     * f0 -> OrExpression()
     *       | AndExpression()
     *       | CompareExpression()
     *       | neqExpression()
     *       | PlusExpression()
     *       | MinusExpression()
     *       | TimesExpression()
     *       | DivExpression()
     *       | ArrayLookup()
     *       | ArrayLength()
     *       | MessageSend()
     *       | PrimaryExpression()
     */
    public void visit(Expression n) {
        n.f0.accept(this);
    }

    /**
     * f0 -> Identifier()
     * f1 -> "&&"
     * f2 -> Identifier()
     */
    public void visit(AndExpression n) {
        System.out.print(replaceIdentifier(n.f0.f0.tokenImage) + " " + n.f1.tokenImage + " " + replaceIdentifier(n.f2.f0.tokenImage));
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
    }

    /**
     * f0 -> Identifier()
     * f1 -> "||"
     * f2 -> Identifier()
     */
    public void visit(OrExpression n) {
        System.out.print(replaceIdentifier(n.f0.f0.tokenImage) + " " + n.f1.tokenImage + " " + replaceIdentifier(n.f2.f0.tokenImage));

        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
    }

    /**
     * f0 -> Identifier()
     * f1 -> "<="
     * f2 -> Identifier()
     */
    public void visit(CompareExpression n) {
        System.out.print(replaceIdentifier(n.f0.f0.tokenImage) + " " + n.f1.tokenImage + " " + replaceIdentifier(n.f2.f0.tokenImage));

        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
    }

    /**
     * f0 -> Identifier()
     * f1 -> "!="
     * f2 -> Identifier()
     */
    public void visit(neqExpression n) {
        System.out.print(replaceIdentifier(n.f0.f0.tokenImage) + " " + n.f1.tokenImage + " " + replaceIdentifier(n.f2.f0.tokenImage));

        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
    }

    /**
     * f0 -> Identifier()
     * f1 -> "+"
     * f2 -> Identifier()
     */
    public void visit(PlusExpression n) {
        System.out.print(replaceIdentifier(n.f0.f0.tokenImage) + " " + n.f1.tokenImage + " " + replaceIdentifier(n.f2.f0.tokenImage));

        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
    }

    /**
     * f0 -> Identifier()
     * f1 -> "-"
     * f2 -> Identifier()
     */
    public void visit(MinusExpression n) {
        System.out.print(replaceIdentifier(n.f0.f0.tokenImage) + " " + n.f1.tokenImage + " " + replaceIdentifier(n.f2.f0.tokenImage));

        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
    }

    /**
     * f0 -> Identifier()
     * f1 -> "*"
     * f2 -> Identifier()
     */
    public void visit(TimesExpression n) {
        System.out.print(replaceIdentifier(n.f0.f0.tokenImage) + " " + n.f1.tokenImage + " " + replaceIdentifier(n.f2.f0.tokenImage));

        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
    }

    /**
     * f0 -> Identifier()
     * f1 -> "/"
     * f2 -> Identifier()
     */
    public void visit(DivExpression n) {
        System.out.print(replaceIdentifier(n.f0.f0.tokenImage) + " " + n.f1.tokenImage + " " + replaceIdentifier(n.f2.f0.tokenImage));

        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
    }

    /**
     * f0 -> Identifier()
     * f1 -> "["
     * f2 -> Identifier()
     * f3 -> "]"
     */
    public void visit(ArrayLookup n) {
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
    }

    /**
     * f0 -> Identifier()
     * f1 -> "."
     * f2 -> "length"
     */
    public void visit(ArrayLength n) {
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
    }

    /**
     * f0 -> Identifier()
     * f1 -> "."
     * f2 -> Identifier()
     * f3 -> "("
     * f4 -> ( ArgList() )?
     * f5 -> ")"
     */
    public void visit(MessageSend n) {
        System.out.print(replaceIdentifier(n.f0.f0.tokenImage) + "." + n.f2.f0.tokenImage + "(");
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
        System.out.print(")");
        n.f5.accept(this);
    }

    /**
     * f0 -> Identifier()
     * f1 -> ( ArgRest() )*
     */
    public void visit(ArgList n) {
        System.out.print(replaceIdentifier(n.f0.f0.tokenImage));
        n.f0.accept(this);
        n.f1.accept(this);
    }

    /**
     * f0 -> ","
     * f1 -> Identifier()
     */
    public void visit(ArgRest n) {
        System.out.print("," + replaceIdentifier(n.f1.f0.tokenImage));
        n.f0.accept(this);
        n.f1.accept(this);
    }

    /**
     * f0 -> IntegerLiteral()
     *       | FloatLiteral()
     *       | TrueLiteral()
     *       | FalseLiteral()
     *       | Identifier()
     *       | ThisExpression()
     *       | ArrayAllocationExpression()
     *       | AllocationExpression()
     *       | NotExpression()
     */
    public void visit(PrimaryExpression n) {
        n.f0.accept(this);
    }

    /**
     * f0 -> <INTEGER_LITERAL>
     */
    public void visit(IntegerLiteral n) {
        System.out.print(n.f0.tokenImage);
        n.f0.accept(this);
    }

    /**
     * f0 -> <FLOAT_LITERAL>
     */
    public void visit(FloatLiteral n) {
        System.out.print(n.f0.tokenImage);
        n.f0.accept(this);
    }

    /**
     * f0 -> "true"
     */
    public void visit(TrueLiteral n) {
        System.out.print(n.f0.tokenImage);
        n.f0.accept(this);
    }

    /**
     * f0 -> "false"
     */
    public void visit(FalseLiteral n) {
        System.out.print(n.f0.tokenImage);
        n.f0.accept(this);
    }

    /**
     * f0 -> <IDENTIFIER>
     */
    public void visit(Identifier n) {

        n.f0.accept(this);
    }

    /**
     * f0 -> "this"
     */
    public void visit(ThisExpression n) {
        n.f0.accept(this);
    }

    /**
     * f0 -> "new"
     * f1 -> "int"
     * f2 -> "["
     * f3 -> Identifier()
     * f4 -> "]"
     */
    public void visit(ArrayAllocationExpression n) {
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
        n.f4.accept(this);
    }

    /**
     * f0 -> "new"
     * f1 -> Identifier()
     * f2 -> "("
     * f3 -> ")"
     */
    public void visit(AllocationExpression n) {
        System.out.print("new " + n.f1.f0.tokenImage + "()");
        n.f0.accept(this);
        n.f1.accept(this);
        n.f2.accept(this);
        n.f3.accept(this);
    }

    /**
     * f0 -> "!"
     * f1 -> Identifier()
     */
    public void visit(NotExpression n) {
        System.out.print("!" + replaceIdentifier(n.f0.tokenImage));

        n.f0.accept(this);
        n.f1.accept(this);
    }

    private String resolveType(Type t) {
        if (t.f0.choice instanceof BooleanType){
            return "boolean";
        } else if (t.f0.choice instanceof IntegerType) {
            return "int";
        } else if (t.f0.choice instanceof FloatType){
            return "float";
        } else if (t.f0.choice instanceof Identifier) {
            return ((Identifier)t.f0.choice).f0.tokenImage;
        }
        return null;
    }

    private void addRegDeclAndAlloc() {
        int numspills = 0;
        for (Map.Entry<String,String> entry: registerAllocation.entrySet()){
            String unambiguousVariableName = entry.getKey();
            String[] parts = unambiguousVariableName.split("\\.");
            if (parts.length == 3){
                String className = parts[0];
                String methodName = parts[1];
                String varName = parts[2];
                if (className.equals(currentClass) && methodName.equals(currentMethod)){
                    String ra = entry.getValue();
                    if (ra.equals("spill")){
                        registerAllocation.put(unambiguousVariableName,String.valueOf(numspills));
                        numspills++;
                    }
                }
            }
        }
        for (int i = 0; i < numRegisters; i++){
            System.out.println("Object R" + i + ";");
        }
        System.out.println("alloca(" + numspills + ");");
    }


    private String replaceIdentifier(String tokenImage) {
        String unambiguousVariableName = currentClass + "." + currentMethod + "." + tokenImage;
        String ra = registerAllocation.get(unambiguousVariableName);
        String type = typeMap.get(unambiguousVariableName);
        if (ra == null){
            return tokenImage;
        }
        if (ra.contains("R")){
            return "((" + type + ") " + ra + ")";
        } else{
            return "((" + type + ") load(" + ra + "))";
        }

    }
}
