//
// Generated by JTB 1.3.2
//


import syntaxtree.*;
import visitor.BB;
import visitor.GJVisitor;
import visitor.Instruction;
import visitor.ProgramCFG;

import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class MethodInliner<R,A> implements GJVisitor<R,A> {
    //
    // Auto class visitors--probably don't need to be overridden.
    //
    private String currentClassName;
    private String currentMethodName;
    private final ProgramCFG programCFG;

    // Constructor to accept ProgramCFG
    public MethodInliner(ProgramCFG programCFG) {
        this.programCFG = programCFG;
    }

    public R visit(NodeList n, A argu) {
        R _ret=null;
        int _count=0;
        for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
        }
        return _ret;
    }

    public R visit(NodeListOptional n, A argu) {
        if ( n.present() ) {
            R _ret=null;
            int _count=0;
            for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
                e.nextElement().accept(this,argu);
                _count++;
            }
            return _ret;
        }
        else
            return null;
    }

    public R visit(NodeOptional n, A argu) {
        if ( n.present() )
            return n.node.accept(this,argu);
        else
            return null;
    }

    public R visit(NodeSequence n, A argu) {
        R _ret=null;
        int _count=0;
        for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
        }
        return _ret;
    }

    public R visit(NodeToken n, A argu) { return null; }

    //
    // User-generated visitor methods below
    //

    /**
     * f0 -> MainClass()
     * f1 -> ( TypeDeclaration() )*
     * f2 -> <EOF>
     */
    public R visit(Goal n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return (R) n;
    }

    /**
     * f0 -> "class"
     * f1 -> Identifier()
     * f2 -> "{"
     * f3 -> "public"
     * f4 -> "static"
     * f5 -> "void"
     * f6 -> "main"
     * f7 -> "("
     * f8 -> "String"
     * f9 -> "["
     * f10 -> "]"
     * f11 -> Identifier()
     * f12 -> ")"
     * f13 -> "{"
     * f14 -> ( VarDeclaration() )*
     * f15 -> ( Statement() )*
     * f16 -> "}"
     * f17 -> "}"
     */
    public R visit(MainClass n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        n.f6.accept(this, argu);
        n.f7.accept(this, argu);
        n.f8.accept(this, argu);
        n.f9.accept(this, argu);
        n.f10.accept(this, argu);
        n.f11.accept(this, argu);
        n.f12.accept(this, argu);
        n.f13.accept(this, argu);
        n.f14.accept(this, argu);
        n.f15.accept(this, argu);
        n.f16.accept(this, argu);
        n.f17.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> ClassDeclaration()
     *       | ClassExtendsDeclaration()
     */
    public R visit(TypeDeclaration n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "class"
     * f1 -> Identifier()
     * f2 -> "{"
     * f3 -> ( VarDeclaration() )*
     * f4 -> ( MethodDeclaration() )*
     * f5 -> "}"
     */
    public R visit(ClassDeclaration n, A argu) {
        currentClassName = n.f1.f0.tokenImage;
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        currentClassName = null;

        return _ret;
    }

    /**
     * f0 -> "class"
     * f1 -> Identifier()
     * f2 -> "extends"
     * f3 -> Identifier()
     * f4 -> "{"
     * f5 -> ( VarDeclaration() )*
     * f6 -> ( MethodDeclaration() )*
     * f7 -> "}"
     */
    public R visit(ClassExtendsDeclaration n, A argu) {
        currentClassName = n.f1.f0.tokenImage;

        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        n.f6.accept(this, argu);
        n.f7.accept(this, argu);
        currentClassName = null;

        return _ret;
    }

    /**
     * f0 -> Type()
     * f1 -> Identifier()
     * f2 -> ";"
     */
    public R visit(VarDeclaration n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "public"
     * f1 -> Type()
     * f2 -> Identifier()
     * f3 -> "("
     * f4 -> ( FormalParameterList() )?
     * f5 -> ")"
     * f6 -> "{"
     * f7 -> ( VarDeclaration() )*
     * f8 -> ( Statement() )*
     * f9 -> "return"
     * f10 -> Identifier()
     * f11 -> ";"
     * f12 -> "}"
     */
    public R visit(MethodDeclaration n, A argu) {
        currentMethodName = n.f2.f0.tokenImage;
        NodeListOptional newVarDecl = new NodeListOptional();  // To hold the modified statement list
        NodeListOptional newStatements = new NodeListOptional(); // To hold new statements inlined

        //System.out.println("Entered method declaration: " + currentMethodName);
        for (Enumeration<Node> e = n.f8.elements(); e.hasMoreElements();){
            Statement stmt = (Statement) e.nextElement();
            Boolean isinlined = false;
            if (stmt.f0.choice instanceof AssignmentStatement){
//                System.out.println("Entered assignment stmt");
                AssignmentStatement assignment = (AssignmentStatement) stmt.f0.choice;
                Expression rightExpr = assignment.f2;
                if (rightExpr.f0.choice instanceof MessageSend){
                    isinlined = true;
                    MessageSend methodCall = (MessageSend) rightExpr.f0.choice;
                    Bindings bindings = (Bindings) argu;
                    String varname = methodCall.f0.f0.tokenImage;
                    String declaredType = bindings.lookupVariable(currentClassName,currentMethodName,varname);
                    String methodName = methodCall.f2.f0.tokenImage;
                    List<String> possibleTypes = bindings.lookupPossibleTypes(declaredType, methodName);
                    if (possibleTypes.size() == 1) {
                        //System.out.println("Inlining method: " + possibleTypes.get(0) + "." + methodName);

                        String resolvedClassName = possibleTypes.get(0);
                        Map<String, String> variableMap = new HashMap<>();
                        NodeOptional parameters = methodCall.f4;

                        // Initialize the Vector to store argument identifiers
                        Vector<Identifier> arguments = new Vector<Identifier>();

// Check if parameters are present
                        if (parameters.present()) {
                            ArgList argList = (ArgList) parameters.node;  // Get the argument list

                            // Add the first argument to the vector (the first element in the argument list)
                            arguments.add(argList.f0);  // Cast the first argument to Identifier

                            // Check for additional arguments (the rest of the arguments)
                            NodeListOptional restArgs = argList.f1;  // This contains the remaining arguments
                            if (restArgs.present()) {
                                for (Node node : restArgs.nodes) {
                                    ArgRest argRest = (ArgRest) node;  // Cast the node to ArgRest
                                    arguments.add(argRest.f1);  // Add the identifier (argument) from ArgRest
                                }
                            }
                        }



                        int paramIndex = 0;
                        Map<String,String> args = bindings.getBindings().get(resolvedClassName).getMethodMetadata().get(methodName).getArguments();
                        for (Map.Entry<String,String> entry: args.entrySet()){
                            String paramName = entry.getKey();  // The parameter name
                            String paramType = entry.getValue();  // The parameter type (e.g., "int", "boolean", etc.)
                            NodeChoice typeChoice;
                            if (paramType.equals("int")) {
                                IntegerType intType = new IntegerType(new NodeToken("int"));
                                typeChoice = new NodeChoice(intType, 2); // Use the correct choice index for IntegerType
                            } else if (paramType.equals("boolean")) {
                                BooleanType boolType = new BooleanType(new NodeToken("boolean"));
                                typeChoice = new NodeChoice(boolType, 1); // Use the correct choice index for BooleanType
                            } else {
                                // For custom class types
                                NodeToken paramTypeToken = new NodeToken(paramType);
                                Identifier typeIdentifier = new Identifier(paramTypeToken);
                                typeChoice = new NodeChoice(typeIdentifier, 3); // Use the correct choice index for Identifier
                            }
                            // Create a VarDecl
                            Type typeNode = new Type(typeChoice);

                            String newParamName = resolvedClassName + "_" + methodName + "_" + paramName;
                            variableMap.put(paramName, newParamName);

                            NodeToken paramIdentifierToken = new NodeToken(newParamName);  // Renamed to avoid conflicts
                            Identifier paramIdentifier = new Identifier(paramIdentifierToken);  // Create an identifier for the parameter
                            VarDeclaration varDecl = new VarDeclaration(typeNode, paramIdentifier);  // Create the variable declaration
                            newVarDecl.addNode(varDecl);  // Add the variable declaration to the list of statements
                            if (paramIndex < arguments.size() ) {
                                // I want you to just pass the string that corresponds to the identifier name of the argument being passed by the methodcall
                                Identifier argumentIdentifier = arguments.get(paramIndex);
                                Expression argExpr = new Expression(new NodeChoice(new PrimaryExpression(new NodeChoice(argumentIdentifier,3)),11));
//                                Expression argExpr = new Expression(new NodeChoice(new PrimaryExpression(new NodeChoice(argumentIdentifier))));
                                AssignmentStatement assignmentStatement = new AssignmentStatement(paramIdentifier,argExpr);
                                newStatements.addNode(assignmentStatement);
                                paramIndex++;
                            }

                        }

                        Transformer transformer = new Transformer(resolvedClassName,methodName,variableMap,assignment.f0.f0.tokenImage,varname);
                        // Get method body statements to inline

                        BB methodBB = programCFG.methodBBSet.get(resolvedClassName + "_" + methodName);
                        if (methodBB != null) {
                           // System.out.println("Found method body, inlining instructions:");
                            for (Instruction i : methodBB.instructions) {
                                if (i.instructionNode != null) {
                                    Node instruction = i.instructionNode;
                                    if (instruction instanceof VarDeclaration) {
                                      //  System.out.println("Var Declaration: Ignored");
                                        VarDeclaration curr = (VarDeclaration) instruction;
                                    } else if (instruction instanceof AssignmentStatement) {
                                       // System.out.println("Assignment Stmt: ");
                                        AssignmentStatement curr = (AssignmentStatement) instruction;
                                        AssignmentStatement transformed = transformer.transform(curr);
                                        newStatements.addNode(transformed);
                                    } else if (instruction instanceof MethodDeclaration) {
                                       // System.out.println("Return stmt: ");
                                        MethodDeclaration curr = (MethodDeclaration) i.instructionNode;
                                        AssignmentStatement transformed = transformer.transform(curr);
                                        newStatements.addNode(transformed);
                                    } else if (instruction instanceof PrintStatement) {
                                       // System.out.println("Print stmt: ");
                                        PrintStatement curr = (PrintStatement) i.instructionNode;
                                        PrintStatement transformed = transformer.transform(curr);
                                        newStatements.addNode(transformed);
                                    } else if (i.instructionNode instanceof ArrayAssignmentStatement) {
                                       // System.out.println("ArrayAssStmt: ");
                                        ArrayAssignmentStatement curr = (ArrayAssignmentStatement) i.instructionNode;
                                        ArrayAssignmentStatement transformed = transformer.transform(curr);
                                        newStatements.addNode(transformed);
                                    } else if (i.instructionNode instanceof FieldAssignmentStatement) {
                                      //  System.out.println("FieldAssStmt");
                                        FieldAssignmentStatement curr = (FieldAssignmentStatement) i.instructionNode;
                                        FieldAssignmentStatement transformed = transformer.transform(curr);
                                        newStatements.addNode(transformed);
                                    } else if (i.instructionNode instanceof IfthenStatement) {
                                       // System.out.println("IfthenStmt: ");
                                        IfthenStatement curr = (IfthenStatement) i.instructionNode;
                                        IfthenStatement transformed = transformer.transform(curr);
                                        newStatements.addNode(transformed);
                                    } else if (i.instructionNode instanceof IfthenElseStatement) {
                                     //   System.out.println("Ifthenelsestmt: ");
                                        IfthenElseStatement curr = (IfthenElseStatement) i.instructionNode;
                                        IfthenElseStatement transformed = transformer.transform(curr);
                                        newStatements.addNode(transformed);
                                    } else if (i.instructionNode instanceof WhileStatement) {
                                      //  System.out.println("Whilestmt");
                                        WhileStatement curr = (WhileStatement) i.instructionNode;
                                        WhileStatement transformed = transformer.transform(curr);
                                        newStatements.addNode(transformed);
                                    } else {
                                     //   System.out.println("Unhandled stmt");
                                    }
                                }
                            }
                        }
                    }
                }
            }
            if (!isinlined){
                newStatements.addNode(stmt);  // Add the current statement to the new statements list
            }
        }
        R _ret=null;
        if (n.f7.nodes == null) {
            n.f7.nodes = new Vector<>();
        }
        for (Node varDeclaration: newVarDecl.nodes){
            VarDeclaration vardecl = (VarDeclaration) varDeclaration;
            n.f7.nodes.add(vardecl);
        }
        n.f8 = newStatements;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        n.f6.accept(this, argu);
        n.f7.accept(this, argu);
        n.f8.accept(this, argu);
        n.f9.accept(this, argu);
        n.f10.accept(this, argu);
        n.f11.accept(this, argu);
        n.f12.accept(this, argu);
        currentMethodName = null;

        return _ret;
    }

    /**
     * f0 -> FormalParameter()
     * f1 -> ( FormalParameterRest() )*
     */
    public R visit(FormalParameterList n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Type()
     * f1 -> Identifier()
     */
    public R visit(FormalParameter n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> ","
     * f1 -> FormalParameter()
     */
    public R visit(FormalParameterRest n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> ArrayType()
     *       | BooleanType()
     *       | IntegerType()
     *       | Identifier()
     */
    public R visit(Type n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "int"
     * f1 -> "["
     * f2 -> "]"
     */
    public R visit(ArrayType n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "boolean"
     */
    public R visit(BooleanType n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "int"
     */
    public R visit(IntegerType n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Block()
     *       | AssignmentStatement()
     *       | ArrayAssignmentStatement()
     *       | FieldAssignmentStatement()
     *       | IfStatement()
     *       | WhileStatement()
     *       | PrintStatement()
     */
    public R visit(Statement n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "{"
     * f1 -> ( Statement() )*
     * f2 -> "}"
     */
    public R visit(Block n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "="
     * f2 -> Expression()
     * f3 -> ";"
     */
    public R visit(AssignmentStatement n, A argu) {


        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "["
     * f2 -> Identifier()
     * f3 -> "]"
     * f4 -> "="
     * f5 -> Identifier()
     * f6 -> ";"
     */
    public R visit(ArrayAssignmentStatement n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        n.f6.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "."
     * f2 -> Identifier()
     * f3 -> "="
     * f4 -> Identifier()
     * f5 -> ";"
     */
    public R visit(FieldAssignmentStatement n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> IfthenElseStatement()
     *       | IfthenStatement()
     */
    public R visit(IfStatement n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "if"
     * f1 -> "("
     * f2 -> Identifier()
     * f3 -> ")"
     * f4 -> Statement()
     */
    public R visit(IfthenStatement n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "if"
     * f1 -> "("
     * f2 -> Identifier()
     * f3 -> ")"
     * f4 -> Statement()
     * f5 -> "else"
     * f6 -> Statement()
     */
    public R visit(IfthenElseStatement n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        n.f6.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "while"
     * f1 -> "("
     * f2 -> Identifier()
     * f3 -> ")"
     * f4 -> Statement()
     */
    public R visit(WhileStatement n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "System.out.println"
     * f1 -> "("
     * f2 -> Identifier()
     * f3 -> ")"
     * f4 -> ";"
     */
    public R visit(PrintStatement n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> OrExpression()
     *       | AndExpression()
     *       | CompareExpression()
     *       | neqExpression()
     *       | PlusExpression()
     *       | MinusExpression()
     *       | TimesExpression()
     *       | DivExpression()
     *       | ArrayLookup()
     *       | ArrayLength()
     *       | MessageSend()
     *       | PrimaryExpression()
     */
    public R visit(Expression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "&&"
     * f2 -> Identifier()
     */
    public R visit(AndExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "||"
     * f2 -> Identifier()
     */
    public R visit(OrExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "<="
     * f2 -> Identifier()
     */
    public R visit(CompareExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "!="
     * f2 -> Identifier()
     */
    public R visit(neqExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "+"
     * f2 -> Identifier()
     */
    public R visit(PlusExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "-"
     * f2 -> Identifier()
     */
    public R visit(MinusExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "*"
     * f2 -> Identifier()
     */
    public R visit(TimesExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "/"
     * f2 -> Identifier()
     */
    public R visit(DivExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "["
     * f2 -> Identifier()
     * f3 -> "]"
     */
    public R visit(ArrayLookup n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "."
     * f2 -> "length"
     */
    public R visit(ArrayLength n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> Identifier()
     * f1 -> "."
     * f2 -> Identifier()
     * f3 -> "("
     * f4 -> ( ArgList() )?
     * f5 -> ")"
     */
    public R visit(MessageSend n, A argu) {

        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        n.f5.accept(this, argu);
        return _ret;
    }


    /**
     * f0 -> Identifier()
     * f1 -> ( ArgRest() )*
     */
    public R visit(ArgList n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> ","
     * f1 -> Identifier()
     */
    public R visit(ArgRest n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> IntegerLiteral()
     *       | TrueLiteral()
     *       | FalseLiteral()
     *       | Identifier()
     *       | ThisExpression()
     *       | ArrayAllocationExpression()
     *       | AllocationExpression()
     *       | NotExpression()
     */
    public R visit(PrimaryExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> <INTEGER_LITERAL>
     */
    public R visit(IntegerLiteral n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "true"
     */
    public R visit(TrueLiteral n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "false"
     */
    public R visit(FalseLiteral n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> <IDENTIFIER>
     */
    public R visit(Identifier n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "this"
     */
    public R visit(ThisExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "new"
     * f1 -> "int"
     * f2 -> "["
     * f3 -> Identifier()
     * f4 -> "]"
     */
    public R visit(ArrayAllocationExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        n.f4.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "new"
     * f1 -> Identifier()
     * f2 -> "("
     * f3 -> ")"
     */
    public R visit(AllocationExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        n.f2.accept(this, argu);
        n.f3.accept(this, argu);
        return _ret;
    }

    /**
     * f0 -> "!"
     * f1 -> Identifier()
     */
    public R visit(NotExpression n, A argu) {
        R _ret=null;
        n.f0.accept(this, argu);
        n.f1.accept(this, argu);
        return _ret;
    }

}
